#!/usr/bin/env python
#
# Hey Emacs, this is -*-python-*-
#
# Copyright 2013 Peter Liljenberg <peter.liljenberg@gmail.com>
#
# Distributed under an MIT license, please see LICENSE in the top dir.

import sys
import argparse

from codplayer import db, player, config

def main(args):
    try:
        cfg = config.Config(args.config)
        database = db.Database(cfg.database)

        if args.debug:
            log_file = sys.stderr
            control_fd = sys.stdin.fileno()
        else:
            sys.exit('non-debug mode not implemented yet')

            #log_file = open(cfg.log_file, 'at')

            #unlink(cfg.control_fifo)
            # TODO: create fifo

    except config.ConfigError, e:
        sys.exit('invalid configuration:\n{0}'.format(e))

    except db.DatabaseError, e:
        sys.exit('error opening database:\n{0}'.format(e))

    # TODO: fork off if not in debug mode
        
    p = player.Player(cfg, database, log_file, control_fd)
    p.run()
            
    

#
# Set up the command argument parsing
#

parser = argparse.ArgumentParser(description = 'codplayer daemon')
parser.add_argument('-c', '--config', help = 'alternative configuration file')
parser.add_argument('-d', '--debug', action = 'store_true',
                    help = 'run in debug mode instead of deamon')

if __name__ == '__main__':
    args = parser.parse_args()
    main(args)
