#!/usr/bin/env python
# Hey Emacs, this is -*-python-*-
#
# codplayer - REST API using bottle.py
#
# Copyright 2014 Peter Liljenberg <peter.liljenberg@gmail.com>
#
# Distributed under an MIT license, please see LICENSE in the top dir.

import sys
import argparse

from codplayer import db
from codplayer import rest
from codplayer import config
from codplayer import full_version

def main(args):
    try:
        cfg = config.RestConfig(args.config)
        database = db.Database(cfg.database)

    except config.ConfigError, e:
        sys.exit('invalid configuration:\n{0}'.format(e))

    except db.DatabaseError, e:
        sys.exit('error opening database:\n{0}'.format(e))

    rest.RestDaemon(cfg, database, debug = args.debug)


parser = argparse.ArgumentParser(description = 'codplayer database REST API')
parser.add_argument('-c', '--config', help = 'alternative configuration file')
parser.add_argument('-d', '--debug', action = 'store_true',
                    help = 'run in debug mode')
parser.add_argument('--version', action = 'version', version = full_version())

if __name__ == '__main__':
    args = parser.parse_args()
    main(args)
        
